[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
delegation_program = "E1bxy4HwKFjPARhVe7NjvoFtynN69C4xNA53uSwruHrP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/tim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
